### ISSUE TITLE
read_scrape statewide bug 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#102]
[This line](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/read_scrape_data.R#L217) drops: 
* Statewide in Vermont because there's a row for out-of-state (`Residents.Tested`)
* Statewide in Maine because there's a row for the youth facility (`Residents.Population` and `Residents.Vadmin`) 

As a result, the sums are under-counting by a lot (e.g. 219 vs. 3,003 for `Residents.Tested` in Vermont, 4 vs. 682 for `Residents.Vadmin` in Maine). 

Options: 
* Rename Statewide to something else (e.g. In-State Total for Vermont, Adult Total for Maine) while crosswalking 
* Change the line to do something else (probably here and in `calc_aggregate` which filters out the opposite rows)

**Comment by hjohns12** [comment]
I'm trying to think about the worst-possible scenario to plan for here. Would it be this? For one state, we have the following: 
- `Residents.Confirmed`, youth, Name = "STATEWIDE"
- `Residents.Confirmed`, adults, facility-level
- `Residents.Deaths`, adults, Name = "STATEWIDE" (no facility-level data for this variable)

This is probs annoyingly complicated but what if we checked the sum of a variable within the state/jurisdiction/age to figure out whether or not to filter STATEWIDE?? ugh

**Comment by erika-tyagi** [comment]
Closing because this was resolved in the last aggregate counts refactoring.
