### ISSUE TITLE
Window to date threshold migration 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#112]
I think the actual implementation of this should be really straightforward once we make some of the higher-level decisions. Initial scoping below, but I'm sure I'm missing things to work out! 

----- 

### Problem 
We don’t want data to disappear when agencies take down dashboards / MP data becomes too old. We also don’t want to report really old data that’s way undercounting “cumulative over the course of the pandemic” (e.g. Oklahoma or Florida data from when they stopped reporting in Oct 20) though. 

### Solution
Use a date threshold to decide when data is Too Old rather than a time window. 

### Files to update

- [x] `GLOBALS` - add default `DATE_THRESHOLD` to pass into the various functions below 
- [x] `read_mpap_data` - add `date_threshold` param, replace the date filter [here](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/read_mpap_data.R#L44)   
- [x] `read_scrape_data` - add `date_threshold` param, update the date filter [here](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/read_scrape_data.R#L191) 
- [x] `calc_aggregate_counts` - add `date_threshold` param, pass that into the `read_mpap_data` and `read_scrape_data` calls 
- [x] `alt_aggregate_counts` - add `date_threshold` param, pass that into the `read_mpap_data` and `read_scrape_data` calls 

Note: we'll also have to update `write_latest_data` in the scraper utilities. 

### Open questions
1. For `read_scrape_data` and `calc_aggregate_counts`, do we want: 
* To replace `window` with `date_threshold`? 
* To be able to use both filters? (i.e. only keep data that is BOTH within the window and after the threshold) 

If we did the former (which I kind of think makes sense...?), I'm wondering if we should still allow a `window` parameter in the various functions (even if it's not used), and then just throw a message saying that the parameter has been depreciated to avoid breaking code. 

2. For population data, I don't think we need to make any updates. I think we still want to fill in `Residents.Population` values if they're within a window of the scraped COVID data date (irrespective of the current date), which [this](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/read_scrape_data.R#L141) would still do - does that make sense though? I'm also wondering if we should bump the default `window_pop` up to like 60 or even 90 given the lag in how agencies update. 

3. What should the `date_threshold` be? `2021-06-01` maybe? Also, is `date_threshold` a reasonable name? 

4. Should we tag a version onto `barstools` with this? Feels like a new era..... 

5. Semi-related but not directly related - we don't want to change anything to account for BOP data (or other places that report declining cumulative counts), right? I know we talked about eventually breaking out multiple variables, but I think that's still further down the line.

**Comment by hjohns12** [comment]
> Open questions
> 1. For `read_scrape_data` and `calc_aggregate_counts`, do we want:
> 
> * To replace `window` with `date_threshold`?
> * To be able to use both filters? (i.e. only keep data that is BOTH within the window and after the threshold)

Replacing `window` with `date_threshold` makes the most sense to me, only because I can't think of a specific scenario when we would want to do the latter (specify both window and date threshold). 

> If we did the former (which I kind of think makes sense...?), I'm wondering if we should still allow a `window` parameter in the various functions (even if it's not used), and then just throw a message saying that the parameter has been depreciated to avoid breaking code.

Allowing users to specify a `window` parameter that doesn't work seems confusing! I'd prefer to break old code, and if we're re-running anything with `window` specified, will need to update the parameter. I could definitely end up hating myself later for saying this :0 

> 1. For population data, I don't think we need to make any updates. I think we still want to fill in `Residents.Population` values if they're within a window of the scraped COVID data date (irrespective of the current date), which [this](https://github.com/uclalawcovid19behindbars/behindbarstools/blob/master/R/read_scrape_data.R#L141) would still do - does that make sense though? I'm also wondering if we should bump the default `window_pop` up to like 60 or even 90 given the lag in how agencies update.

That makes sense to me. You know better than anyone about the population data frequency, and so if you think bumping it up to 60 or 90 days make sense, I'm good with that -- I feel like 90 days is a good upper bound to set. 

> 2. What should the `date_threshold` be? `2021-06-01` maybe? Also, is `date_threshold` a reasonable name?

I think`date_cutoff` might be slightly more clear, but `date_threshold` works just as well!

> 3. Should we tag a version onto `barstools` with this? Feels like a new era.....

HELL YES!!!

> 4. Semi-related but not directly related - we don't want to change anything to account for BOP data (or other places that report declining cumulative counts), right? I know we talked about eventually breaking out multiple variables, but I think that's still further down the line.

Agree that's a separate process but one we need to deal with ~eventually~

**Comment by erika-tyagi** [comment]
Things to remember to do between integrating this and running the scrapers: 
- [ ] Update `write_latest_data`
- [ ] Update diagnostics script
