### ISSUE TITLE
Population source ambiguity in `read_scrape_data`

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/behindbarstools#29]
https://github.com/uclalawcovid19behindbars/behindbarstools/blob/e9d59a1a771b82ea68c51defab181067e7305fe9/R/read_scrape_data.R#L106

Not super sure how to make this better without messing up the Google Sheet

**Comment by nmmarquez** [comment]
If i understand the new facility sheet correctly wont it have one column that is the correct merged in Pop data. If thats the case can we just remove the portion of this function which calls the pop_data function and just use the facility info pop data?

**Comment by hjohns12** [comment]
Absolutely. Will leave this issue open for now as a reminder to remove the merge_pop bit of code once we get the new facility info sheet hooked up.
