### ISSUE TITLE
Update facility xwalk functions 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#34]
To make the new crosswalk process work bug-free, we will need to: 

- [x] Add `fac_data.csv` and `fac_spellings.csv` to `GLOBALS.R` 

Fix variable names and files paths in:
- [x] `read_fac_spellings`
- [x] `read_fac_info`
- [x] `clean_facility_name`
- [x] `is_fac_name`
- [x]  `merge_facility_info`
- [x] `read_scrape_data`

- [x] New federal indicator added to case_when in `clean_facility_name` 
- [x] Consider any other federal changes that might need to happen in `clean_facility_name` 

- [x]  make sure new merges have a failsafe for non merges (aka they still get on the website)
- [x] population data will now come directly from the facility info sheet which needs to change in get_scrape_data

- [x] After merging in fac_info, create jurisdiction by coalesce. Use EITHER `Jurisdiction` from fac_data OR jurisdiction from scraper

- [x] Once the merge happens, change the URL path to `fac_data.csv` and `fac_spellings.csv` in `GLOBALS.R` to the main branch rather than `fac_sheet_restruct` one

**Comment by erika-tyagi** [comment]
Actually, this is a good impetus to just set up CI for the package repo!

**Comment by erika-tyagi** [comment]
> * [ ]   `merge_facility_info`

I'm probably missing something, but can we just use `Facility.ID` to merge here? We generated the IDs based on the separate federal + non-federal merges, so I think we can leverage having IDs that are (hopefully!) reliable to make this simpler?

**Comment by nmmarquez** [comment]
Yup! I believe we said we should move to merge by ID in the code transition

**Comment by hjohns12** [comment]
> > * [ ]    `clean_facility_name`
> > * [ ]    `merge_facility_info`
> 
> I'm probably missing something, but can we just use `Facility.ID` to merge here? We generated the IDs based on the separate federal + non-federal merges, so I think we can leverage having IDs that are (hopefully!) reliable to make this simpler?

Sorry, I totally forgot about this plan! Let's do it!
