### ISSUE TITLE
MAJOR REVISISONS FOR FAC_INFO REPO CHANGES

### ISSUE THREAD

**Issue by nmmarquez** [uclalawcovid19behindbars/behindbarstools#45]
We should have a separate branch to coordinate with the major changes being made to the fac_info repo. Some of these include

- account for the variable name changes
- federal merges now should rely on the is_federal flag which is binary
- make sure new merges have a failsafe for non merges (aka they still get on the website)
- population data will now come directly from the facility info sheet which needs to change in `get_scrape_data`

**Comment by hjohns12** [comment]
Closing this because https://github.com/uclalawcovid19behindbars/behindbarstools/issues/34
