### ISSUE TITLE
Historical data? 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#49]
* Maybe add historical data to `read_scrape_data` when `all_dates = TRUE` if a historical file for that state exists? 
* Probably post-database existing?

**Comment by hjohns12** [comment]
Wondering how this fits into the new old / old old distinction to be made amongst historical data files. See https://github.com/uclalawcovid19behindbars/historical-data/issues/10 for more details

**Comment by nmmarquez** [comment]
@hjohns12 Yeah I think that would cover it! getting it to work within read_scrape_data might be tricky but we can tackle that down the road.

**Comment by hjohns12** [comment]
I'm probably missing something, but I think that even once all of the data is contained within the historical data repo, we're still going to need to write a function to read it in. Unless that happened already? Help

**Comment by nmmarquez** [comment]
Yup yup, it will be an easy function to write but im gonna reoprn this until we do it

**Comment by hjohns12** [comment]
Updated with https://github.com/uclalawcovid19behindbars/historical-data/commit/5e0ac5f6001f85210540184293a436565e8ecf10
