### ISSUE TITLE
Add Residents.Population to read_scrape_data

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#52]
Unclear if this is a good idea or not?  

Right now we only get `Population.Feb20` from `read_scrape_data`, it would be nice to also pull `Residents.Population` (i.e. the latest population data is the reporting agency reports updated population data on the source that we scrape) – so have two population variables (Feb20 and current) in the latest data. 

* Harmonize (1) [Github data](adult_facility_covid_counts_today_latest.csv), (2) [Google sheet data](https://docs.google.com/spreadsheets/d/1X6uJkXXS-O6eePLxw2e4JeRtM41uPZ2eRcOA_HkPVTk/edit#gid=1641553906), (3) what comes out of `read_scrape_data`? 
* Make necessary changes in scraper code? 
* Make sure variable names are different, pulling from the right place, and clearly documented

**Comment by nmmarquez** [comment]
I dont think anything needs to happen in the main scraper pipeline, and only minor changes that we will need to do are in the `production/post_run.R`. So we have two population variables `Residents.Population` which is tied to a scrape date and `Population.Feb20` which is the population data on Feb 1st that helps make our data more comparable.

**Comment by erika-tyagi** [comment]
Resolution: Do NOT include for now, integrate this into the historical data pipelines instead.
