### ISSUE TITLE
Clean_facility_name bugs

### ISSUE THREAD

**Issue by hjohns12** [uclalawcovid19behindbars/behindbarstools#60]
https://github.com/uclalawcovid19behindbars/behindbarstools/blob/42efa24835f330fd124212d376a38dfbdb1297fb/R/clean_facility_name.R#L72

Is this a bug in clean_facility_name()? To create the array of possible fac_spellings in `federal_xwalk`, we're filtering down to immigration and federal jurisdiction facilities. But when filtering the input data, we're limiting to only federal jurisdictions. I think this means we will never clean immigration jurisdictions, even if we have alternate spellings for them. 

Question -- do we want to merge immigration jurisdictions on state, name, and jurisdiction? Or just name, as we do for federal facilities? 

cc @nmmarquez @erika-tyagi

**Comment by hjohns12** [comment]
Pt 2: 

`federal_bool` should most include "Jurisdiction" if it exists. Not sure why this wasn't added in during the xwalk overhaul -- was that a conscious choice? I think it was probably an oversight

https://github.com/uclalawcovid19behindbars/behindbarstools/blob/42efa24835f330fd124212d376a38dfbdb1297fb/R/clean_facility_name.R#L47

**Comment by hjohns12** [comment]
Pt 3: 

More surprising behavior within this function. This test implies that we don't need jurisdiction to find a match. 

```
test <- tibble(Name = "BLACKWATER CF", State = "Florida", Jurisdiction = NA)%>% 
      add_row(Name = "CALHOUN CI", State = "Florida", Jurisdiction = NA) %>%
      add_row(Name = "CALHOUN CI", State = "Florida", Jurisdiction = "state") 

out_test <- behindbarstools::clean_facility_name(test) 

## RESULT
  Name                             State   Jurisdiction jurisdiction Facility.ID
  <chr>                            <chr>   <chr>        <chr>              <dbl>
1 BLACKWATER CF                    Florida NA           NA                    NA
2 CALHOUN CORRECTIONAL INSTITUTION Florida NA           NA                   246
3 CALHOUN CORRECTIONAL INSTITUTION Florida state        NA                   246
```

**Comment by erika-tyagi** [comment]
> https://github.com/uclalawcovid19behindbars/behindbarstools/blob/42efa24835f330fd124212d376a38dfbdb1297fb/R/clean_facility_name.R#L72
> 
> Is this a bug in clean_facility_name()? To create the array of possible fac_spellings in `federal_xwalk`, we're filtering down to immigration and federal jurisdiction facilities. But when filtering the input data, we're limiting to only federal jurisdictions. I think this means we will never clean immigration jurisdictions, even if we have alternate spellings for them.
> 
> Question -- do we want to merge immigration jurisdictions on state, name, and jurisdiction? Or just name, as we do for federal facilities?
> 
> cc @nmmarquez @erika-tyagi

All ICE facilities have ICE in the name coming out of the scrapers (and they're like federal facilities in that we don't know their state when scraping?) so I've been merging state and county facilities on `Name` + `State` and then federal and immigration facilities on `Name` (looking for name matches within federal and immigration only). So I think the answer is just name, and we can do the merge within the same universe as federal facilities?

**Comment by erika-tyagi** [comment]
> Pt 2:
> 
> `federal_bool` should include "Jurisdiction" if it exists. Not sure why this wasn't added in during the xwalk overhaul -- was that a conscious choice? I think it was probably an oversight
> 
> https://github.com/uclalawcovid19behindbars/behindbarstools/blob/42efa24835f330fd124212d376a38dfbdb1297fb/R/clean_facility_name.R#L47

I think you're right! Still confused on where we're using `Jurisdiction` vs. `jurisdiction` at this point, but we should definitely use both to be safe.

**Comment by nmmarquez** [comment]
> Is this a bug in clean_facility_name()? To create the array of possible fac_spellings in federal_xwalk, we're filtering down to immigration and federal jurisdiction facilities. 

Immigration facilities from the scraper have a State indicator of "federal" so they are captured by the federal filter and merges are happening succesfully. This was something that I believe we agrreed upon in the immigration PR 

> Question -- do we want to merge immigration jurisdictions on state, name, and jurisdiction? Or just name, as we do for federal facilities?

Just name and I believe this is already happening, I just tested using behindbarstools and immigration rows do have Facility.ID

**Comment by hjohns12** [comment]
More notes on this issue (feel free to ignore) 

Things that are happening within `clean_facility_name`:

1. Create a variable called `federal_bool`that looks for an array of possible variables that all might contain the word "federal"

- Note: should website include "BOP", designation should be TRUE in `federal_bool`. This is not currently included in the case_when statement
- Note: currently treating NA Jurisdiction as NOT federal in `federal_bool`. Need to think long and hard about this

2. Separate the crosswalk into federal and non-federal crosswalk based on `Jurisdiction` 
3. Separate the data into federal and non-federal based on `federal_bool`
4. Merge data with fac_spellings on Name or Name and State based off of `federal_bool`
5. Bind federal and non-federal rows
6. Return data

**Comment by hjohns12** [comment]
What do we want to happen when `Jurisdiction` exists in fac_spellings but NOT in the data? Do we want to fill that in? 

This is currently happening within `merge_facility_info`
