### ISSUE TITLE
Fix multiple jurisdiction columns 

### ISSUE THREAD

**Issue by erika-tyagi** [uclalawcovid19behindbars/behindbarstools#70]
`read_scrape_data()` currently has two jurisdiction columns: 
1. `Jurisdiction` from the info sheets 
2. `jurisdiction` from the scraped data

We definitely want to coalesce these, but unclear which we want to prioritize when both are non-NA. This only happens for a few TX jails (state or county?) right now. 

I sort of think we should prioritize `jurisdiction`, since assigning jurisdiction based on the agency that reports data on an entity seems more systematic than a manual process. I also think it's confusing if the scraper says a facility is one jurisdiction and we're matching IDs based on that jurisdiction... but then we change that jurisdiction through the linkage process? I'll defer to whatever others think makes the most sense though! (cc: @nmmarquez, @mceverett8) 

@hjohns12 - I know you've been deepest in the weeds on the various functions to merge crosswalks into data, do you maybe want to figure out how/where to handle this?

**Comment by erika-tyagi** [comment]
Update: keep BOTH columns, rename `jurisdiction` to something like `jurisdiction_scraper`.

**Comment by hjohns12** [comment]
Did it here https://github.com/uclalawcovid19behindbars/behindbarstools/commit/ae5d99f1c0a57a6b52a167acf95987d94b3f552a
